import type { Metadata } from "next";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOption } from "./api/auth/[...nextauth]/options";
import SessionSetter from "@/lib/SessionSetter";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOption);

  return (
    <html lang="en">
      <body className={`antialiased bg-black`} suppressHydrationWarning>
        {children}
        <SessionSetter session={session} />
      </body>
    </html>
  );
}
